version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '8888:80'
    volumes:
      - ./html:/var/www/html
      - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
volumes:
  db:
